### ISSUE TITLE
Try to use and study internal sample?

### ISSUE THREAD

**Issue by Vytek** [AF-GRILL/DISPluginForUnity#2]
Even though the Asset Store says the sample is "coming soon" (https://assetstore.unity.com/packages/tools/network/grill-dis-241766) I saw that there is a sample in the Asset folder which I tried to load in Unity. Running the example nothing happens and I would very much like to understand how it all works. Is it necessary to use https://github.com/VeriorPies/ParrelSync to have two instances of the Editor or does the example not work? Greetings and I hope you can help us as we would like to use this fantastic asset!

**Comment by Vytek** [comment]
I have trying to build the sample scene and run the editor: 

SocketException: Di norma è consentito un solo utilizzo di ogni indirizzo di socket (protocollo/indirizzo di rete/porta).

System.Net.Sockets.Socket.Bind (System.Net.EndPoint localEP) (at <1e13855442cf491a8b11d7de866cc016>:0)
System.Net.Sockets.UdpClient..ctor (System.Int32 port, System.Net.Sockets.AddressFamily family) (at <1e13855442cf491a8b11d7de866cc016>:0)
System.Net.Sockets.UdpClient..ctor (System.Int32 port) (at <1e13855442cf491a8b11d7de866cc016>:0)
GRILLDIS.UDPReceiverMulti.UDPReceiverMulti.BeginReceive () (at Assets/GRILLDIS/DISPluginContent/Scripts/UDPReceiverMulti.cs:94)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Threading.ThreadHelper.ThreadStart () (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs)

**Comment by jhuggins0214** [comment]
This error happens as the UDP sockets that get opened by our plugin are blocking. If multiple sockets are opened that try to bind to an address that is already bound and blocked, then this error will be given.

We plan to make the sockets nonblocking in a future release to avoid this from happening.

**Comment by Vytek** [comment]
How to fix to make sample run fine?

**Comment by jhuggins0214** [comment]
Run a single instance of the editor and verify that the send and receive sockets are set up to be able to communicate. These are located on the DISManager game object inside of its attached PDU Sender script and PDU Receiver script respectively. For testing you can set them up as shown in the below image. Setting them up this way will allow for the single instance of the editor to talk to itself.
![image](https://user-images.githubusercontent.com/57466472/222015457-7e04521e-9a29-4b5f-87e9-cc61dac7c637.png)


It also looks like we input non-matching entity types for the DIS_Sender prefab and the Sample_DISEnumerationMapping asset which could also be why you're not seeing anything. We'll fix that on our next push.
In the meantime, set one of them to have a matching entity type of the other. One way to do so is to go into the DIS_Sender game object in the DemoScene and change the "Current Entity Type" variable on the DIS Send Component script in the Inspector panel to be as shown in the image.
![image](https://user-images.githubusercontent.com/57466472/222014872-d19e891a-87a6-4e41-8ae6-c8a6ec9829f2.png)

This could also be done the opposite way as well. You could go into the Sample_DISEnumerationMapping asset in the GRILL_DIS/DISPluginContent/Samples folder and either add a new Entity Type for the Test Entity that matches the one in the DIS_Sender game object or change the existing Entity Type to be that of the one in the DIS_Sender game object.

If everything is set up correctly, you should see a black box appear in the same location as the cylinder in the DemoScene and the box should follow the cylinder around if you move the cylinder at all.

Let me know if this fixes your issue.

**Comment by Vytek** [comment]
Thank you! I am studing and trying all! See you...
