### ISSUE TITLE
Unity Plugin for CSharpDis7

### ISSUE THREAD

**Issue by pd3a** [AF-GRILL/DISPluginForUnity#3]
How to make Unity plugin with CSharpDis7 from Open DIS

**Comment by jhuggins0214** [comment]
If you want to use CSharpDis7, you'll have to download the Open DIS CSharpDis7 library and add it into a Unity project alongside our plugin. Then go into the scripts of our plugin and replace any 'using' statement that includes a CSharpDis6 library with the new CSharpDis7 libraries you want to use.

We only tested our plugin using the CSharpDis6 libraries, so changing to CSharpDis7 may cause some other errors you may need to fix as well.
